### ISSUE TITLE
add missing 'import traceback'

### ISSUE THREAD

**Issue by xor512** [damsgithub/myzuka-club.py#1]
In case of errors I'm seeing this:

** Error: Cannot download URL: https://myzcloud.me/artist/51467/steven-wilson, reason: name 'traceback' is not defined **

As suggested in https://github.com/nickoala/telepot/issues/70 adding missing import should fix this.

PS As musicmp3spb.org is dead, it's really nice that you've created scrappers for other sites. Thank you very much!

**Comment by damsgithub** [comment]
Hi!

I just saw your comment today, I'm not very good at using github... Anyway I'm happy that it is usefull for some other people than me ;)

Thanks
